/* automatically generated by rust-bindgen 0.71.1 */

pub const VEF_PREVIEW_PING_NAME: &[u8; 20] = b"vsql::preview::ping\0";
pub const VEF_PREVIEW_PING_ABI_VERSION: u32 = 1;
pub type vef_ping_fn = ::std::option::Option<unsafe extern "C" fn() -> u64>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vef_preview_ping_t {
    pub version: u32,
    pub ping: vef_ping_fn,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vef_preview_ping_t"][::std::mem::size_of::<vef_preview_ping_t>() - 16usize];
    ["Alignment of vef_preview_ping_t"][::std::mem::align_of::<vef_preview_ping_t>() - 8usize];
    ["Offset of field: vef_preview_ping_t::version"]
        [::std::mem::offset_of!(vef_preview_ping_t, version) - 0usize];
    ["Offset of field: vef_preview_ping_t::ping"]
        [::std::mem::offset_of!(vef_preview_ping_t, ping) - 8usize];
};
