/* automatically generated by rust-bindgen 0.71.1 */

pub const VEF_PREVIEW_SQL_QUERY_NAME: &[u8; 25] = b"vsql::preview::sql_query\0";
pub const VEF_PREVIEW_SQL_QUERY_ABI_VERSION: u32 = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vef_sql_session_t {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vef_sql_result_t {
    _unused: [u8; 0],
}
pub const vef_sql_diag_severity_t_VEF_SQL_DIAG_NOTE: vef_sql_diag_severity_t = 1;
pub const vef_sql_diag_severity_t_VEF_SQL_DIAG_WARNING: vef_sql_diag_severity_t = 2;
pub const vef_sql_diag_severity_t_VEF_SQL_DIAG_ERROR: vef_sql_diag_severity_t = 3;
pub type vef_sql_diag_severity_t = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vef_sql_diag_t {
    pub errno_: u32,
    pub severity: vef_sql_diag_severity_t,
    pub sqlstate: *const ::std::os::raw::c_char,
    pub message: *const ::std::os::raw::c_char,
    pub message_len: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vef_sql_diag_t"][::std::mem::size_of::<vef_sql_diag_t>() - 32usize];
    ["Alignment of vef_sql_diag_t"][::std::mem::align_of::<vef_sql_diag_t>() - 8usize];
    ["Offset of field: vef_sql_diag_t::errno_"]
        [::std::mem::offset_of!(vef_sql_diag_t, errno_) - 0usize];
    ["Offset of field: vef_sql_diag_t::severity"]
        [::std::mem::offset_of!(vef_sql_diag_t, severity) - 4usize];
    ["Offset of field: vef_sql_diag_t::sqlstate"]
        [::std::mem::offset_of!(vef_sql_diag_t, sqlstate) - 8usize];
    ["Offset of field: vef_sql_diag_t::message"]
        [::std::mem::offset_of!(vef_sql_diag_t, message) - 16usize];
    ["Offset of field: vef_sql_diag_t::message_len"]
        [::std::mem::offset_of!(vef_sql_diag_t, message_len) - 24usize];
};
pub type vef_sql_open_session_fn = ::std::option::Option<
    unsafe extern "C" fn(handle: *mut vef_thread_handle_t) -> *mut vef_sql_session_t,
>;
pub type vef_sql_close_session_fn =
    ::std::option::Option<unsafe extern "C" fn(session: *mut vef_sql_session_t)>;
pub type vef_sql_execute_fn = ::std::option::Option<
    unsafe extern "C" fn(
        session: *mut vef_sql_session_t,
        sql: *const ::std::os::raw::c_char,
        sql_len: usize,
    ) -> *mut vef_sql_result_t,
>;
pub type vef_sql_row_cb = ::std::option::Option<
    unsafe extern "C" fn(
        row: *mut *const ::std::os::raw::c_char,
        lengths: *const ::std::os::raw::c_ulong,
        num_columns: ::std::os::raw::c_uint,
        ctx: *mut ::std::os::raw::c_void,
    ) -> bool,
>;
pub type vef_sql_for_each_row_fn = ::std::option::Option<
    unsafe extern "C" fn(
        session: *mut vef_sql_session_t,
        sql: *const ::std::os::raw::c_char,
        sql_len: usize,
        cb: vef_sql_row_cb,
        ctx: *mut ::std::os::raw::c_void,
    ) -> *mut vef_sql_result_t,
>;
pub type vef_sql_fetch_row_fn = ::std::option::Option<
    unsafe extern "C" fn(
        result: *mut vef_sql_result_t,
        row_out: *mut *mut *const ::std::os::raw::c_char,
        lengths_out: *mut *const ::std::os::raw::c_ulong,
    ) -> bool,
>;
pub type vef_sql_num_columns_fn = ::std::option::Option<
    unsafe extern "C" fn(result: *mut vef_sql_result_t) -> ::std::os::raw::c_uint,
>;
pub type vef_sql_close_result_fn =
    ::std::option::Option<unsafe extern "C" fn(result: *mut vef_sql_result_t)>;
pub type vef_sql_has_error_fn =
    ::std::option::Option<unsafe extern "C" fn(result: *const vef_sql_result_t) -> bool>;
pub type vef_sql_get_error_fn = ::std::option::Option<
    unsafe extern "C" fn(result: *const vef_sql_result_t, out: *mut vef_sql_diag_t) -> bool,
>;
pub type vef_sql_warning_count_fn = ::std::option::Option<
    unsafe extern "C" fn(result: *const vef_sql_result_t) -> ::std::os::raw::c_uint,
>;
pub type vef_sql_get_warning_fn = ::std::option::Option<
    unsafe extern "C" fn(
        result: *const vef_sql_result_t,
        i: ::std::os::raw::c_uint,
        out: *mut vef_sql_diag_t,
    ) -> bool,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct vef_preview_sql_query_t {
    pub version: u32,
    pub open_session: vef_sql_open_session_fn,
    pub close_session: vef_sql_close_session_fn,
    pub execute: vef_sql_execute_fn,
    pub fetch_row: vef_sql_fetch_row_fn,
    pub num_columns: vef_sql_num_columns_fn,
    pub close_result: vef_sql_close_result_fn,
    pub for_each_row: vef_sql_for_each_row_fn,
    pub has_error: vef_sql_has_error_fn,
    pub get_error: vef_sql_get_error_fn,
    pub warning_count: vef_sql_warning_count_fn,
    pub get_warning: vef_sql_get_warning_fn,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of vef_preview_sql_query_t"][::std::mem::size_of::<vef_preview_sql_query_t>() - 96usize];
    ["Alignment of vef_preview_sql_query_t"]
        [::std::mem::align_of::<vef_preview_sql_query_t>() - 8usize];
    ["Offset of field: vef_preview_sql_query_t::version"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, version) - 0usize];
    ["Offset of field: vef_preview_sql_query_t::open_session"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, open_session) - 8usize];
    ["Offset of field: vef_preview_sql_query_t::close_session"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, close_session) - 16usize];
    ["Offset of field: vef_preview_sql_query_t::execute"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, execute) - 24usize];
    ["Offset of field: vef_preview_sql_query_t::fetch_row"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, fetch_row) - 32usize];
    ["Offset of field: vef_preview_sql_query_t::num_columns"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, num_columns) - 40usize];
    ["Offset of field: vef_preview_sql_query_t::close_result"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, close_result) - 48usize];
    ["Offset of field: vef_preview_sql_query_t::for_each_row"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, for_each_row) - 56usize];
    ["Offset of field: vef_preview_sql_query_t::has_error"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, has_error) - 64usize];
    ["Offset of field: vef_preview_sql_query_t::get_error"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, get_error) - 72usize];
    ["Offset of field: vef_preview_sql_query_t::warning_count"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, warning_count) - 80usize];
    ["Offset of field: vef_preview_sql_query_t::get_warning"]
        [::std::mem::offset_of!(vef_preview_sql_query_t, get_warning) - 88usize];
};
