//! Safe Rust SDK for writing VillageSQL extension functions (VDFs).
//!
//! # Quick start
//!
//! 1. Add `vsql = { path = "..." }` to your `Cargo.toml` with `crate-type = ["cdylib"]`.
//! 2. Write a function with the signature `fn(&[InValue]) -> VdfReturn`.
//! 3. Declare the extension with the [`extension!`] macro.
//!
//! See `examples/rot13` for a complete working extension.

pub use paste;
pub use vsql_sys as sys;

use std::ffi::c_char;
use vsql_sys::{
    vef_func_desc_t, vef_protocol_t_VEF_PROTOCOL_2, vef_registration_t,
    vef_signature_t, vef_type_t, vef_version_t,
    vef_type_id_VEF_TYPE_INT, vef_type_id_VEF_TYPE_REAL, vef_type_id_VEF_TYPE_STRING,
    vef_return_value_type_t_VEF_RESULT_ERROR, vef_return_value_type_t_VEF_RESULT_NULL,
    vef_return_value_type_t_VEF_RESULT_VALUE, vef_return_value_type_t_VEF_RESULT_WARNING,
    vef_vdf_args_t, vef_vdf_result_t, VEF_MAX_ERROR_LEN,
};

// ── Public types ──────────────────────────────────────────────────────────────

/// SQL type identifier for a VDF parameter or return type.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum Type {
    String,
    Real,
    Int,
}

impl Type {
    fn to_raw(self) -> vef_type_t {
        let id = match self {
            Type::String => vef_type_id_VEF_TYPE_STRING,
            Type::Real => vef_type_id_VEF_TYPE_REAL,
            Type::Int => vef_type_id_VEF_TYPE_INT,
        };
        vef_type_t {
            id,
            custom_type: std::ptr::null(),
        }
    }
}

/// A single input value delivered to a VDF for one row.
///
/// Always check for [`InValue::Null`] before attempting to read the inner value.
#[derive(Debug)]
pub enum InValue<'a> {
    Null,
    String(&'a str),
    Real(f64),
    Int(i64),
}

/// The value a VDF returns for one row.
#[derive(Debug)]
pub enum VdfReturn {
    /// SQL NULL result.
    Null,
    /// A string value.
    String(std::string::String),
    /// A floating-point value.
    Real(f64),
    /// An integer value.
    Int(i64),
    /// Row-level warning: execution continues, NULL is returned for this row.
    Warning(std::string::String),
    /// Fatal error: statement execution is aborted.
    Error(std::string::String),
}

impl VdfReturn {
    pub fn null() -> Self { Self::Null }
    pub fn string(s: impl Into<std::string::String>) -> Self { Self::String(s.into()) }
    pub fn real(v: f64) -> Self { Self::Real(v) }
    pub fn int(v: i64) -> Self { Self::Int(v) }
    pub fn warning(msg: impl Into<std::string::String>) -> Self { Self::Warning(msg.into()) }
    pub fn error(msg: impl Into<std::string::String>) -> Self { Self::Error(msg.into()) }
}

// ── Descriptor used by the extension! macro ──────────────────────────────────

/// Compile-time descriptor for a single VDF. Built by the [`extension!`] macro;
/// you do not construct this directly.
pub struct FuncDescriptor {
    /// Null-terminated SQL function name (static lifetime).
    pub sql_name: *const c_char,
    /// Parameter types.
    pub params: &'static [Type],
    /// Return type.
    pub returns: Type,
    /// The `extern "C"` trampoline generated by the macro.
    pub trampoline: unsafe extern "C" fn(
        *mut vsql_sys::vef_context_t,
        *mut vef_vdf_args_t,
        *mut vef_vdf_result_t,
    ),
    pub deterministic: bool,
}

// SAFETY: FuncDescriptor only holds 'static pointers and fn pointers.
unsafe impl Send for FuncDescriptor {}
unsafe impl Sync for FuncDescriptor {}

// ── Internal runtime helpers (called by macro-generated code) ─────────────────

/// Convert raw Protocol-2 VDF arguments into a `&[InValue]` slice and call `f`.
///
/// # Safety
/// Caller must ensure `args` and `result` are valid for the duration of the call.
pub unsafe fn dispatch_vdf(
    f: fn(&[InValue]) -> VdfReturn,
    args: *mut vef_vdf_args_t,
    result: *mut vef_vdf_result_t,
) {
    let args = &*args;
    let result = &mut *result;

    // Protocol 2: values is an array of *mut vef_invalue_t pointers.
    let value_count = args.value_count as usize;
    let raw_vals =
        std::slice::from_raw_parts(args.__bindgen_anon_1.values, value_count);

    let mut in_values: Vec<InValue> = Vec::with_capacity(value_count);
    for &ptr in raw_vals {
        let v = &*ptr;
        if v.is_null {
            in_values.push(InValue::Null);
            continue;
        }
        let iv = match v.type_ {
            t if t == vef_type_id_VEF_TYPE_STRING => {
                let anon = &v.__bindgen_anon_1.__bindgen_anon_1;
                let bytes = std::slice::from_raw_parts(anon.str_value as *const u8, anon.str_len);
                // VillageSQL guarantees UTF-8 for STRING columns.
                InValue::String(std::str::from_utf8_unchecked(bytes))
            }
            t if t == vef_type_id_VEF_TYPE_REAL => {
                InValue::Real(v.__bindgen_anon_1.real_value)
            }
            t if t == vef_type_id_VEF_TYPE_INT => {
                InValue::Int(v.__bindgen_anon_1.int_value)
            }
            _ => InValue::Null,
        };
        in_values.push(iv);
    }

    write_result(f(&in_values), result);
}

unsafe fn write_result(ret: VdfReturn, result: &mut vef_vdf_result_t) {
    match ret {
        VdfReturn::Null => {
            result.type_ = vef_return_value_type_t_VEF_RESULT_NULL;
        }
        VdfReturn::String(s) => {
            result.type_ = vef_return_value_type_t_VEF_RESULT_VALUE;
            let anon = &mut result.__bindgen_anon_1.__bindgen_anon_1;
            let bytes = s.as_bytes();
            let write_len = bytes.len().min(anon.max_str_len);
            std::ptr::copy_nonoverlapping(bytes.as_ptr(), anon.str_buf as *mut u8, write_len);
            result.actual_len = write_len;
        }
        VdfReturn::Real(v) => {
            result.type_ = vef_return_value_type_t_VEF_RESULT_VALUE;
            result.__bindgen_anon_1.real_value = v;
        }
        VdfReturn::Int(v) => {
            result.type_ = vef_return_value_type_t_VEF_RESULT_VALUE;
            result.__bindgen_anon_1.int_value = v;
        }
        VdfReturn::Warning(msg) => {
            result.type_ = vef_return_value_type_t_VEF_RESULT_WARNING;
            write_error_msg(msg.as_bytes(), result.error_msg);
        }
        VdfReturn::Error(msg) => {
            result.type_ = vef_return_value_type_t_VEF_RESULT_ERROR;
            write_error_msg(msg.as_bytes(), result.error_msg);
        }
    }
}

unsafe fn write_error_msg(msg: &[u8], buf: *mut c_char) {
    let max = (VEF_MAX_ERROR_LEN as usize).saturating_sub(1);
    let n = msg.len().min(max);
    std::ptr::copy_nonoverlapping(msg.as_ptr(), buf as *mut u8, n);
    *buf.add(n) = 0;
}

/// Allocate a `vef_registration_t` from a slice of [`FuncDescriptor`]s and
/// return a leaked pointer. Called by the macro-generated `vef_register`.
///
/// # Safety
/// All `FuncDescriptor` fields must be valid for `'static`.
pub unsafe fn build_registration(descs: &[FuncDescriptor]) -> *mut vef_registration_t {
    // Allocate each func descriptor and its signature.
    let mut func_ptrs: Vec<*mut vef_func_desc_t> = Vec::with_capacity(descs.len());

    for d in descs {
        // Param type array.
        let params: Box<[vef_type_t]> = d.params.iter().map(|t| t.to_raw()).collect();
        let param_count = params.len() as u32;
        let params_ptr = Box::into_raw(params) as *const vef_type_t;

        // Signature.
        let sig = Box::new(vef_signature_t {
            param_count,
            params: params_ptr,
            return_type: d.returns.to_raw(),
        });
        let sig_ptr = Box::into_raw(sig);

        // Function descriptor.
        let func = Box::new(vef_func_desc_t {
            protocol: vef_protocol_t_VEF_PROTOCOL_2,
            name: d.sql_name,
            signature: sig_ptr,
            vdf: Some(d.trampoline),
            prerun: None,
            postrun: None,
            buffer_size: 0,
            deterministic: d.deterministic,
            clear: None,
            accumulate: None,
        });
        func_ptrs.push(Box::into_raw(func));
    }

    let func_count = func_ptrs.len() as u32;
    let funcs_box: Box<[*mut vef_func_desc_t]> = func_ptrs.into_boxed_slice();
    let funcs_ptr = Box::into_raw(funcs_box) as *mut *mut vef_func_desc_t;

    let reg = Box::new(vef_registration_t {
        protocol: vef_protocol_t_VEF_PROTOCOL_2,
        error_msg: std::ptr::null_mut(),
        deprecated_extension_version: std::ptr::null(),
        sdk_version: vef_version_t {
            major: 0,
            minor: 1,
            patch: 0,
            extra: std::ptr::null(),
        },
        deprecated_extension_name: std::ptr::null(),
        func_count,
        funcs: funcs_ptr,
        type_count: 0,
        types: std::ptr::null_mut(),
        required_capability_count: 0,
        required_capabilities: std::ptr::null(),
    });

    Box::into_raw(reg)
}

/// Free all memory allocated by [`build_registration`].
///
/// # Safety
/// `registration` must have been returned by [`build_registration`].
pub unsafe fn free_registration(registration: *mut vef_registration_t) {
    if registration.is_null() {
        return;
    }
    let reg = Box::from_raw(registration);

    let funcs =
        std::slice::from_raw_parts_mut(reg.funcs, reg.func_count as usize);
    for &func_ptr in funcs.iter() {
        let func = Box::from_raw(func_ptr);
        let sig = Box::from_raw(func.signature);
        // Reconstruct the param slice and drop it.
        drop(Box::from_raw(std::slice::from_raw_parts_mut(
            sig.params as *mut vef_type_t,
            sig.param_count as usize,
        )));
        drop(sig);
        drop(func);
    }
    // Reconstruct the funcs slice and drop it.
    drop(Box::from_raw(std::slice::from_raw_parts_mut(
        reg.funcs,
        reg.func_count as usize,
    )));
    drop(reg);
}

// ── extension! macro ──────────────────────────────────────────────────────────

/// Declare a VillageSQL extension and generate the `vef_register` /
/// `vef_unregister` C entry points.
///
/// # Syntax
///
/// ```ignore
/// vsql::extension! {
///     funcs: [
///         vsql::func!(my_impl, "sql_name", [vsql::Type::String] -> vsql::Type::String),
///         vsql::func!(other_impl, "other_name", [vsql::Type::Int, vsql::Type::Int] -> vsql::Type::Int,
///                     deterministic: true),
///     ]
/// }
/// ```
///
/// Each `vsql::func!(...)` entry describes one VDF. The first argument is the
/// Rust function (must be in scope), the second is the SQL-visible name, then
/// the parameter list and return type, and an optional `deterministic: bool`.
#[macro_export]
macro_rules! extension {
    (
        funcs: [ $( $func_desc:expr ),* $(,)? ]
    ) => {
        #[no_mangle]
        pub unsafe extern "C" fn vef_register(
            _arg: *const $crate::sys::vef_register_arg_t,
        ) -> *mut $crate::sys::vef_registration_t {
            let descs: &[$crate::FuncDescriptor] = &[$($func_desc),*];
            $crate::build_registration(descs)
        }

        #[no_mangle]
        pub unsafe extern "C" fn vef_unregister(
            _arg: *const $crate::sys::vef_unregister_arg_t,
            registration: *mut $crate::sys::vef_registration_t,
        ) {
            $crate::free_registration(registration);
        }
    };
}

/// Build a [`FuncDescriptor`] for one VDF and generate its `extern "C"` trampoline.
///
/// Used inside [`extension!`]; see that macro for usage examples.
#[macro_export]
macro_rules! func {
    // With explicit deterministic flag.
    ($impl_fn:ident, $sql_name:literal, [$($param:expr),* $(,)?] -> $ret:expr,
     deterministic: $det:expr) => {{
        $crate::paste::paste! {
            unsafe extern "C" fn [< __vsql_trampoline_ $impl_fn >](
                _ctx: *mut $crate::sys::vef_context_t,
                args: *mut $crate::sys::vef_vdf_args_t,
                result: *mut $crate::sys::vef_vdf_result_t,
            ) {
                $crate::dispatch_vdf($impl_fn, args, result);
            }
            static [< __VSQL_PARAMS_ $impl_fn:upper >]: &[$crate::Type] = &[$($param),*];
            $crate::FuncDescriptor {
                sql_name: concat!($sql_name, "\0").as_bytes().as_ptr()
                    as *const ::std::os::raw::c_char,
                params: [< __VSQL_PARAMS_ $impl_fn:upper >],
                returns: $ret,
                trampoline: [< __vsql_trampoline_ $impl_fn >],
                deterministic: $det,
            }
        }
    }};
    // Without deterministic flag (defaults to false).
    ($impl_fn:ident, $sql_name:literal, [$($param:expr),* $(,)?] -> $ret:expr) => {
        $crate::func!($impl_fn, $sql_name, [$($param),*] -> $ret, deterministic: false)
    };
}
